### ISSUE TITLE
Set max to more than 100

### ISSUE THREAD

**Issue by cutiko** [zurche/plain-pie#1]
Greetings

I like this for a project, but I dont see a method to set the max (like setMax in progressBar). Is always 100 or just by default?

Thanks

**Comment by zurche** [comment]
Hello @cutiko , yes, by default it is set to be 100, as you can see. Feel free to fork the library and submit a pull request with your change if you have an Idea. Otherwise, I will add this feature whenever I find free time to work with the lib. Thank you!

**Comment by galadril** [comment]
Then this is now fixed in the latest version :)

```

PieView pie4 = (PieView)findViewById(R.id.pieView4);

pie4.setMaxPercentage(200);

pie4.setPercentage(120);

```

**Comment by galadril** [comment]
This case can be closed
