### ISSUE TITLE
Not Visible at 0%

### ISSUE THREAD

**Issue by aolives** [zurche/plain-pie#13]
Haven't tested, but I think,
`        if (mPercentage != 0) {
            canvas.drawArc(mRect, -90, this.mAngle, true, mPercentageFill);
            canvas.drawArc(mRectCent, -90, 360, true, mCenterFill);
        }`
could be,
`        if (mPercentage != 0) {
            canvas.drawArc(mRect, -90, this.mAngle, true, mPercentageFill);
            canvas.drawArc(mRectCent, -90, 360, true, mCenterFill);
        } else {
             canvas.drawArc(mRectCent, -90, 360, true, mCenterFill);
        }`

**Comment by zurche** [comment]
Hi! @aolives thanks for submiting the issue, I noticed that when the 0 was set the percentage was not shown. I fixed this in the v0.2.4 version. But I still notice that for the 0% scenario the background of the widget is not shown and maybe your suggestion would fix it.

Will check for this solution to update it.

Regards!

**Comment by hamedsilver** [comment]
I have the same problem on v0.2.4 version

**Comment by zurche** [comment]
Fixed in version v0.2.9 and updated demo app with latest version and working sample of this scenario. Thanks for the feedback @aolives and @hamedsilver
