### ISSUE TITLE
Add animations for filling the bar?

### ISSUE THREAD

**Issue by galadril** [zurche/plain-pie#5]
Maybe it would make the design better to add some load animations?
Great lib btw!

**Comment by zurche** [comment]
Absolutely, this is a must have in the upcoming version. Thanks for pointing it out.

**Comment by galadril** [comment]
https://github.com/galadril/plain-pie

I've added 2 things on a fork:
- pie arc animator
- showcase example activity

If you like... I can do a merge request? :-)

To set the animation on the arc.. just do the following:

```

        PieAngleAnimation animation = new PieAngleAnimation(pieViewAnimated, (75/100)*360);
        animation.setDuration(1000);
        pieViewAnimated.startAnimation(animation);


```

**Comment by zurche** [comment]
That looks great! Do create the merge request, I'll test and integrate asap.

**Comment by zurche** [comment]
Added to release 0.2.1.
